### ISSUE TITLE
NestJs ^9.0.0 - '"@nestjs/common"' has no exported member named 'HttpService'

### ISSUE THREAD

**Issue by itzikntn** [AlariCode/nestjs-consul#17]
node_modules/nestjs-consul/dist/consul.service.d.ts:2:10 - error TS2724: '"@nestjs/common"' has no exported member named 'HttpService'. Did you mean 'HttpServer'?

package.json:
 "nestjs-consul": "^1.4.0", 
"@nestjs/common": "^9.0.4",
"@nestjs/core": "^9.0.4"

![image](https://user-images.githubusercontent.com/38310394/179912646-ad068f00-8005-4417-8227-44a159b79bb0.png)

please fix it 

Best Regards
Itzik natan

**Comment by AlariCode** [comment]
@itzikntn, updated for NestJS 9 in version 1.5.0

**Comment by itzikntn** [comment]
Great !
Have a good day 😊

בתאריך יום ד׳, 20 ביולי 2022, 16:39, מאת Anton Larichev ‏<
***@***.***>:
